package com.gorki.config;

import org.apache.commons.lang.StringUtils;

import javax.servlet.Filter;
import javax.servlet.FilterChain;
import javax.servlet.FilterConfig;
import javax.servlet.ServletException;
import javax.servlet.ServletRequest;
import javax.servlet.ServletResponse;
import javax.servlet.http.HttpServletRequest;
import java.io.IOException;

/**
 * This filter is used in production, to serve static resources generated by "grunt build".
 * <p/>
 * <p>
 * It is configured to serve resources from the "dist" directory, which is the Grunt destination directory.
 * </p>
 */
public class StaticResourcesProductionFilter implements Filter {

	@Override
	public void init(final FilterConfig filterConfig) throws ServletException {
		// Nothing to initialize
	}

	@Override
	public void destroy() {
		// Nothing to destroy
	}

	@Override
	public void doFilter(final ServletRequest request, final ServletResponse response, final FilterChain chain)
		throws IOException, ServletException {
		final HttpServletRequest httpRequest = (HttpServletRequest) request;
		final String contextPath = ((HttpServletRequest) request).getContextPath();
		String requestURI = httpRequest.getRequestURI();
		requestURI = StringUtils.substringAfter(requestURI, contextPath);
		if (StringUtils.equals("/", requestURI)) {
			requestURI = "/index.html";
		}
		final String newURI = "/dist" + requestURI;
		System.err.println(newURI);
		request.getRequestDispatcher(requestURI).forward(request, response);
	}
}
